export const CREATE_JOB = "CREATE_JOB";
export const RETRIEVE_JOBS = "RETRIEVE_JOBS";
export const UPDATE_JOB = "UPDATE_JOB";
export const DELETE_JOB = "DELETE_JOB";
export const DELETE_ALL_JOBS = "DELETE_ALL_JOBS";

export const CREATE_APPLICATION = "CREATE_APPLICATION";
export const DELETE_APPLICATION = "DELETE_APPLICATION";
export const RETRIVE_APPLICATIONS = "RETRIEVE_APPLICATIONS";

// auth constants
export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const REGISTER_FAIL = "REGISTER_FAIL";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAIL = "LOGIN_FAIL";
export const LOGOUT = "LOGOUT";



export const SET_MESSAGE = "SET_MESSAGE";
export const CLEAR_MESSAGE = "CLEAR_MESSAGE";